### ISSUE TITLE
last fm dataset link failed

### ISSUE THREAD

**Issue by KimRasak** [wmeirui/CSRM_SIGIR2019#1]
The link of last fm dataset seems unavailable.
The posted link is: https://www.dtic.upf.edu/~ocelma/MusicRecommendationDataset/lastfm-1K.html
Could you please upload your copy of dataset? BaiduNetDisk or Github are both ok!

**Comment by DebonairLi** [comment]
您好，我也遇到了同样的问题，请问这个问题解决了吗？谢谢

**Comment by fionaJin** [comment]
运行lastfm数据，出现错误：
Epoch  0 Update  6300 Loss  7.08898
Epoch  0 Update  6400 Loss  7.088235
Epoch  0 Update  6500 Loss  7.087676
Epoch  0 Update  6600 Loss  nan
Traceback (most recent call last):
  File "main.py", line 97, in <module>
    main()
  File "main.py", line 94, in main
    model.train(train, valid, test, result_path)
  File "/content/drive/My Drive/CSRM/csrm.py", line 268, in train
    valid_evaluation, session_memory_state = self.pred_evaluation(Validation_data, kf_valid, session_memory_state)
  File "/content/drive/My Drive/CSRM/csrm.py", line 210, in pred_evaluation
    ranks = (pred.T > np.diag(pred.T[batch_label])).sum(axis=0) + 1  # np.diag(preds.T[targets]) each bacth target"s score
IndexError: index 39180 is out of bounds for axis 0 with size 39164
请问如何解决？

**Comment by kangshitao** [comment]
> The link of last fm dataset seems unavailable.
> The posted link is: https://www.dtic.upf.edu/~ocelma/MusicRecommendationDataset/lastfm-1K.html
> Could you please upload your copy of dataset? BaiduNetDisk or Github are both ok!



> 您好，我也遇到了同样的问题，请问这个问题解决了吗？谢谢
you can reference this link: http://ocelma.net/MusicRecommendationDataset/lastfm-1K.html
